# Generated by Django 5.0.6 on 2024-10-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("specials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="special",
            name="limitations",
            field=models.TextField(null=True),
        ),
    ]
