# Generated by Django 5.0.4 on 2024-04-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("address", models.CharField()),
                ("city", models.CharField()),
                ("state", models.CharField()),
                ("country", models.CharField()),
                ("zipcode", models.CharField()),
                ("google_link", models.URLField(null=True)),
            ],
        ),
    ]
