# Generated by Django 5.0.6 on 2024-10-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField()),
                ("address", models.CharField()),
                ("phone_number", models.CharField(null=True)),
                ("website", models.CharField(null=True)),
                ("google_place_id", models.CharField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
