# Generated by Django 5.0.6 on 2024-10-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="google_url",
            field=models.CharField(null=True),
        ),
    ]
